=== re-motion/Relinq-SqlBackend/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "AdditionalBuildMetadata": {
          "type": "string",
          "description": "Additional build metadata that is attached to the assembly informational version"
        },
        "AssemblySigningKeyFile": {
          "type": "string",
          "description": "Path to the key file containing the signing key"
        },
        "Configurations": {
          "type": "array",
          "description": "Configuration to build - Default is 'Debug' (local) or 'Release' (server)",
          "items": {
            "type": "string"
          }
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "DependDBNugetConfig": {
          "type": "string"
        },
        "DependDBNuGetSources": {
          "type": "string"
        },
        "DependDBProjectBranch": {
          "type": "string"
        },
        "DependDBProjectImportNotificationMailAddress": {
          "type": "string"
        },
        "DependDBProjectImportNotificationMailAddressCc": {
          "type": "string"
        },
        "DependDBProjectName": {
          "type": "string"
        },
        "DependDBProjectVersion": {
          "type": "string"
        },
        "DependDBRetentionTime": {
          "type": "string"
        },
        "DependDBTargetFramework": {
          "type": "string"
        },
        "DependDBTrackedReferences": {
          "type": "string"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TestHost",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "LogFolder": {
          "type": "string",
          "description": "Path to the log folder where log files are put"
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "OutputFolder": {
          "type": "string",
          "description": "Path to the output folder where build artifacts are put"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "AddRemotionPackagingArtefacts",
              "Build",
              "CIBuild",
              "Clean",
              "CreateTestMatrix",
              "CreateTestPlan",
              "DetermineBuildMetadata",
              "DetermineProjectMetadata",
              "DetermineTestResources",
              "FullBuild",
              "GenerateDependDBOutput",
              "GenerateSbom",
              "NightlyBuild",
              "Pack",
              "Restore",
              "Test",
              "VerifyTestParameters"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "AddRemotionPackagingArtefacts",
              "Build",
              "CIBuild",
              "Clean",
              "CreateTestMatrix",
              "CreateTestPlan",
              "DetermineBuildMetadata",
              "DetermineProjectMetadata",
              "DetermineTestResources",
              "FullBuild",
              "GenerateDependDBOutput",
              "GenerateSbom",
              "NightlyBuild",
              "Pack",
              "Restore",
              "Test",
              "VerifyTestParameters"
            ]
          }
        },
        "TempFolder": {
          "type": "string",
          "description": "Path to the temp folder where temporary build files are put"
        },
        "TestConfigurations": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Debug",
              "Release"
            ]
          }
        },
        "TestExecutionRuntimes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Docker_Win_NET462",
              "Docker_Win_NET472",
              "Docker_Win_NET48",
              "LocalMachine"
            ]
          }
        },
        "TestFilter": {
          "type": "string",
          "description": "Executes only tests that match the specified test filter"
        },
        "TestPlatforms": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "x64",
              "x86"
            ]
          }
        },
        "TestSqlServers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "NoDB",
              "SqlServer2014",
              "SqlServer2016",
              "SqlServer2017",
              "SqlServer2019",
              "SqlServer2022",
              "SqlServerDefault"
            ]
          }
        },
        "TestTargetRuntimes": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "NET462",
              "NET472",
              "NET48"
            ]
          }
        },
        "UseReleaseVersioning": {
          "type": "boolean",
          "description": "Uses release instead of debug versioning when determining the build versions"
        },
        "VcsUrlTemplate": {
          "type": "string"
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== re-motion/Relinq-SqlBackend/.nuke/parameters.json
{
  "$schema": "./build.schema.json",
  "Solution": "Relinq-SqlBackend.sln",
  "DependDBProjectName": "re-motion Framework re-linq",
  "DependDBRetentionTime": "10",
  "DependDBProjectBranch": "Main",
  "DependDBProjectImportNotificationMailAddress": "nonexistent@nonexistent.nonexistent",
  "DependDBProjectImportNotificationMailAddressCc": "nonexistent@nonexistent.nonexistent",
  "DependDBTrackedReferences": "Remotion.*",
  "DependDBNugetConfig": "~/nuget.config",
  "DependDBTargetFramework": "net462",
  "VcsUrlTemplate": "example.com"
}
